test_that("pypdf parser extracts core AcroForm mechanics from a synthetic PDF", {
  available <- tryCatch(suppressWarnings(reticulate::py_module_available("pypdf")), error = function(e) FALSE)
  skip_if_not(available, "Python/pypdf unavailable")
  module <- tryCatch(bcapture:::ensure_acroform_python(), error = function(e) NULL)
  skip_if(is.null(module), "Python/pypdf unavailable")
  fixture <- testthat::test_path("fixtures", "synthetic_acroform.py")
  helper <- new.env()
  reticulate::source_python(fixture, envir = helper)
  pdf <- tempfile(fileext = ".pdf")
  helper$create_synthetic_acroform(pdf)
  parsed <- reticulate::py_to_r(module$extract_form(pdf))
  expect_equal(parsed$number_of_fields, 4L)
  expect_equal(parsed$number_of_widgets, 4L)
  fields <- bcapture:::field_rows_to_tibble(parsed$fields)
  expect_true(all(c("default_value", "options", "field_flags", "is_multiselect") %in% names(fields)))
  expect_equal(fields$value[fields$field == "button"], "1")
  expect_equal(fields$value_raw[fields$field == "button"], "1")
  expect_equal(fields$states[fields$field == "button"], "Off|1|3")
  expect_equal(fields$options[fields$field == "choice"], "A|B|C")
  expect_true(fields$is_multiselect[fields$field == "multichoice"])
  expect_equal(fields$default_value[fields$field == "choice"], "Select or Type")
})

test_that("Epi batch rejects an incompatible structured AcroForm", {
  available <- tryCatch(suppressWarnings(reticulate::py_module_available("pypdf")), error = function(e) FALSE)
  skip_if_not(available, "Python/pypdf unavailable")
  skip_if(is.null(tryCatch(bcapture:::ensure_acroform_python(), error = function(e) NULL)), "Python/pypdf unavailable")
  helper <- new.env()
  reticulate::source_python(testthat::test_path("fixtures", "synthetic_acroform.py"), envir = helper)
  input <- tempfile("epi-in-")
  output <- tempfile("epi-out-")
  dir.create(input)
  helper$create_synthetic_acroform(file.path(input, "not_epi.pdf"))
  manifest <- extract_epi(input, output, quiet = TRUE)
  expect_equal(manifest$status, "failed")
  expect_equal(manifest$failure_type, "unexpected_form_type")
  expect_true(file.exists(file.path(output, "extraction_manifest.csv")))
})
